### ISSUE TITLE
Unit & Integration Testing

### ISSUE THREAD

**Issue by chand1012** [multisig-labs/app.gogopool.com#115]
After the Create Minipool page decided to stop working on @emersoncloud and I for seemingly no reason, I think we should take a step back and get some unit tests working, both at the component and the hook level. Here is the current list that needs implemented. 

- [ ] Brainstorm an way to easily test web3 calls. I'm thinking our best option is to use a tool like [Caddy](https://caddyserver.com/) to mock respond to API calls.
- [ ] #54 
- [ ] #55 
- [ ] #52 
- [ ] #53
- [ ] Automate the unit tests with GH Actions.

**Comment by 0xju1ie** [comment]
made into an epic
