### ISSUE TITLE
Front End - Minipool Notification

### ISSUE THREAD

**Issue by WillDosSantos** [multisig-labs/app.gogopool.com#207]
Be sure to create some sort of info pill or disclaimer confirming and explaining minipool usage and rules.

Comments from Slack:
**Julie**
`there should be a disclaimer in the frontend that users cannot cancel their minipools UNLESS there is not enough liquidity in the pool AND they have been waiting for 5 days`
**JohnnyG**
`I dont think we need something as drastic as a pop up or checkbox. The user knows they are locking up funds for a minipool. We could use a box with some descriptive text like "When you create a minipool, GoGoPool will try to match you up with enough Liquid Staker funds to launch your node as a validator. Hopefully this happens within a few minutes, but if it takes longer than 5 days you can come back here and cancel your minipool and get your funds back".`

**Comment by 0xju1ie** [comment]
This has been iterated on in the issue linked above - and we have removed the 5 day requirement for canceling a minipool. If the user is in prelaunch, they can cancel
