### ISSUE TITLE
Frontend Telemetry

### ISSUE THREAD

**Issue by chand1012** [multisig-labs/app.gogopool.com#218]
Frontend telemetry can be a powerful tool to improve the user experience because it provides valuable insights into how users interact with the application and can help identify areas for improvement. It will allow us to track when users leave due to some issue with user experience or a lack of guidance. We should still have some form of "Contact Us" button that persuades a user to contact the team if they're still experiencing issues, but most users will opt for another product, which is why we need telemetry. 

I recommend [Sentry](https://sentry.io/welcome/) for frontend telemetry. Another good option is [NewRelic](https://newrelic.com/platform/browser-monitoring).

**Comment by 0xju1ie** [comment]
We have completed this with the integration of Sentry
