### ISSUE TITLE
Populate end time when start time is populated

### ISSUE THREAD

**Issue by emersoncloud** [multisig-labs/app.gogopool.com#297]
When there is a known start time, also populate the end time with start time + duration. 

This is a bad example because there's no start time yet, but hopefully you get the idea
![image](https://github.com/multisig-labs/app.gogopool.com/assets/13784188/90bbaaf2-c014-403e-b831-5bf4814020cb)

**Comment by 0xju1ie** [comment]
@emersoncloud can you elaborate on this? is this still an issue and if so, where should this be displayed?

if it is no longer necessary, please close it
