### ISSUE TITLE
Always show next rewards date on minipool dashboard

### ISSUE THREAD

**Issue by emersoncloud** [multisig-labs/app.gogopool.com#309]
<img width="785" alt="Screenshot 2023-05-30 at 3 05 17 PM" src="https://github.com/multisig-labs/app.gogopool.com/assets/13784188/aae89b88-8a96-4ecf-8bb0-53636459ad0d">

We should always show users this next rewards date

**Comment by emersoncloud** [comment]
This date is wrong - or is the previous rewards date
![image](https://github.com/multisig-labs/app.gogopool.com/assets/13784188/a469a60b-4c00-4144-aff8-84db9c61de3c)

**Comment by jacktrusler** [comment]
This is solved by issue #392
