### ISSUE TITLE
reorganize the sidebar

### ISSUE THREAD

**Issue by gatesyp** [multisig-labs/app.gogopool.com#328]
right now, the sidebar is 

- Welcome
- Dashboard
- Liquid Stake
- Node Operator
- Docs

it should be: 
- Welcome
- Node Operator
- Dashboard
- Docs

https://www.notion.so/multisiglabs/reorganizing-sidebar-tODO-turn-into-a-GH-issue-90df31301fdc420cb97f279a766cf0cb?pvs=4

**Comment by WillDosSantos** [comment]
@gatesyp I'm going to create a new issue for this the information has changed from this initial request
