### ISSUE TITLE
swap positions of "liquid staking" with "View Documentation" , and delete the liquid staking sidebar navigation button

### ISSUE THREAD

**Issue by gatesyp** [multisig-labs/app.gogopool.com#329]
![CleanShot 2023-06-15 at 13.52.45@2x.png](https://images.zenhubusercontent.com/63b48ef86e6c7a3d8f42c5d1/2365edb0-2ec3-4d77-a373-48097046ead6)

- [ ] Instead of "View Documentation" at the bottom, it should say "Liquid Stake", and link to https://app.gogopool.com/liquid-staking
- [ ] Delete "Liquid Stake" from the sidebar

**Comment by 0xju1ie** [comment]
taken care of with #354
