### ISSUE TITLE
Handle big numbers on all input forms

### ISSUE THREAD

**Issue by emersoncloud** [multisig-labs/app.gogopool.com#341]
When you parse an input as a number, anything more than 7 precision points turns into a scientific notation number, which then fails to parse later into a BigNumber. 

When possible take input as String and convert straight to BigNumber. Use BigNumber everywhere for math and sending to contracts.

**Comment by emersoncloud** [comment]
- [ ] Change all input forms to not error if the number gets too big or has weird formatting. Unify how we're handling number inputs. 
- [ ] Use toFixed(4) instead of 2
- [ ] use Number(formatEther(...)) instead of +formatEther(...)

**Comment by jacktrusler** [comment]
closing in favor of #406
