### ISSUE TITLE
Welcome Page (Getting Started) Redesign

### ISSUE THREAD

**Issue by WillDosSantos** [multisig-labs/app.gogopool.com#353]
**Page**
https://app.gogopool.com/welcome

**Problem:**
Currently, when customers go to our app they are greeted with a Welcome Screen that contains different aspects of our product and where/how to get started. In it's current state, the Welcome screen has become a bit of a UX problem for our Node Operator customers as they find it difficult and confusing as to what to click on and where to go. They want to get to launching a validator faster.

**Solution**
We have new update to the Welcome Screen (hence forth Getting Started Page) that will help clarify the workflow of setting up a validator through a Minipool. We include an example of ROI, in addition to yoking our mission and documentation to the page.

**Figma Comp**
[Here is a link to the comp](https://www.figma.com/file/UMPEc0eW9iZyx5UlBXpCdi/Product-Design---GoGoPool?type=design&node-id=4257%3A8584&mode=design&t=tU62mS7ZLRECYgzQ-1). You must have a Figma account to view this page.

**Comment by WillDosSantos** [comment]
@jacktrusler This is ready to go for you

**Comment by jacktrusler** [comment]
Closed with PR #375
