### ISSUE TITLE
FE(Nav-Sidebar)

### ISSUE THREAD

**Issue by WillDosSantos** [multisig-labs/app.gogopool.com#354]
**Current Sidebar**
https://app.gogopool.com/welcome

**Problem**
Our sidebar has links and nav items that detract from the Minipool creation experience. Our customer feedback is that the sidebar causes confusion as to where to go to begin the Minipool launch. The order of nav items has also been a pain point regarding the hierarchy of importance and does not meet the basic expectations of our Minipool customer base.

**Solution**
Reorder/organize the sidebar to meet the UX requirements of our Minipool customer base with updated links.

**Figma Comp**
[Here is a link to the comp](https://www.figma.com/file/UMPEc0eW9iZyx5UlBXpCdi/Product-Design---GoGoPool?type=design&node-id=4257%3A8584&mode=design&t=tU62mS7ZLRECYgzQ-1). You must have a Figma account in order to view it.

**Comment by WillDosSantos** [comment]
@jacktrusler This is ready to go for you

**Comment by jacktrusler** [comment]
Closed with PR #409
