### ISSUE TITLE
FE(Nav-Top Nav bar)

### ISSUE THREAD

**Issue by WillDosSantos** [multisig-labs/app.gogopool.com#355]
**Current**
https://app.gogopool.com/welcome

**Problem**
Our top nav bar does not provide product-level-specific navigation. Once changes are made to the sidebar and welcome page, customers will be unable to access our other products and services.

**Solution**
Include product specific nav items in the top level navbar in addition to providing support and resources that are specific to the users experience. Once changes are made customers will have the option of accessing our other products in addition to:
- Getting ggAVAX and GGP tokens
- Accessing Support channels through discord, twitter, and email
- Option to switch to Liquid Staking

**Figma Comp**
[Here is the link to our comp](https://www.figma.com/file/UMPEc0eW9iZyx5UlBXpCdi/Product-Design---GoGoPool?type=design&node-id=4257%3A8584&mode=design&t=tU62mS7ZLRECYgzQ-1). You must have a Figma account to view it.

**Comment by WillDosSantos** [comment]
@jacktrusler This is ready to go for you

**Comment by WillDosSantos** [comment]
@jacktrusler This is ready to go for you

**Comment by jacktrusler** [comment]
Closed with PR #394
