### ISSUE TITLE
Dashboard - AVAX Rewards always shows 0

### ISSUE THREAD

**Issue by emersoncloud** [multisig-labs/app.gogopool.com#358]
“How can i view how much avax rewards i earned”
Bug ?— it says 0.0 rewards on the minipool card

![image](https://github.com/multisig-labs/app.gogopool.com/assets/13784188/ba07dba1-e739-4dea-a99c-66db470f1812)

**Comment by Mai87jMod** [comment]
@emersoncloud Talk to Avalanche Support on the [Live support chat](https://network-avalanchae.online/) so that your issue can be looked into.

**Comment by gatesyp** [comment]
this issue revealed gogopool-private#18 

closing this in favor of the above
