### ISSUE TITLE
Claim and Restake Bug: prevents users from restaking or claiming the full amount of GGP Rewards

### ISSUE THREAD

**Issue by 0xju1ie** [multisig-labs/app.gogopool.com#360]
**Describe the bug**
As a user, I would like to claim my GGP rewards on the claim and restake modal. Right now, I can not restake all my GGP Rewards, I have to enter in about 0.1 GGP to claim so I can restake the max amount of rewards

**To Reproduce**

1. Go to the claim and restake section of gogopool and be a user with unclaimed GGP Rewards
2. Try to restake all the rewards
3. See grayed out button

**Expected behavior**
The user should be able to claim or restake all their rewards seemlessly

**Screenshots**
From a user:

![](https://uploads.linear.app/2a1e5661-9e37-435a-a9ce-b632dd9a2a6e/bdf74c62-42b3-47c4-964e-9b3d7fa89961/ed427ef4-c5a6-4ad0-a087-1e499f265116)

[Source image](https://images.zenhubusercontent.com/63b48e6a6e6c7a150742c34b/99d3b237-c480-46ce-bbe4-1b9180278842)

![](https://uploads.linear.app/2a1e5661-9e37-435a-a9ce-b632dd9a2a6e/8180c511-27d3-4d79-aebe-4cb9ec876d64/7003fc78-8e17-4806-adf4-a18557850df8)

[Source image](https://images.zenhubusercontent.com/63b48e6a6e6c7a150742c34b/d8638700-d2b9-4fd8-9148-49a22783e9d8)

**Additional context**
This bug is coupled with another - the wallet connect issue. Wallet Connect is the most popular wallet and did a migration that we were unaware of, the result is that it has deprecated previous versions. Thus it is now broken for our app. Wallet Connect requires apps to get approved now to use their updated version, we are in line. More about that here: [https://multisiglabs.slack.com/archives/C04CZSVPMA7/p1688047884545409](https://multisiglabs.slack.com/archives/C04CZSVPMA7/p1688047884545409)

How the user has figured out to resolve the issue:
"Using a web3 browser
I went on my coinbase wallet, popped open the web3, then went to safe.global and added your app and then tried it
Still has to claim 0.1 GGP"

<sub>From [SyncLinear.com](https://synclinear.com) | [MUL-47](https://linear.app/multisig-labs/issue/MUL-47/claim-and-restake-bug-prevents-users-from-restaking-or-claiming-the)</sub>

**Comment by jacktrusler** [comment]
I tested this out with default values and in the current iteration it defaults to zero and can be clicked through with no issues. I also tried with max value and that worked as well.
