### ISSUE TITLE
Dashboard - when validator cycles, "Created" shows as "-" on the minipool's card

### ISSUE THREAD

**Issue by gatesyp** [multisig-labs/app.gogopool.com#361]
![image](https://github.com/multisig-labs/app.gogopool.com/assets/13278417/d9973400-2265-4d47-9ab8-bcd3ca534f97)

**Comment by jacktrusler** [comment]
This might be fixed by dashboard redesign, look into after finished with #390

**Comment by WillDosSantos** [comment]
We have this represented under the Launch Time Column on the table in the dashboard. Closing this issue
