### ISSUE TITLE
Discuss - A user tried to use an existing node when creating a minipool.

### ISSUE THREAD

**Issue by emersoncloud** [multisig-labs/app.gogopool.com#366]
Wasn't clear that they were supposed to be making a new new node with this.

**Comment by gatesyp** [comment]
closing in favor of adding to a new "priorities" db , for the future grooming meeting
[link](https://www.notion.so/multisiglabs/Discuss-A-user-tried-to-use-an-existing-node-when-creating-a-minipool-d4f05bf4820543a4b1c655682338d1bc?pvs=4)

flow will be : 

net new ideas go into "priorities" db -> grooming meetings to triage + select top 10 for backlog -> sprint planning meeting to pick from backlog

**Comment by gatesyp** [comment]
ugg we have a lot of these

instead of closing them all ill just link to them in our prio db 

reopening

**Comment by 0xju1ie** [comment]
how do we want to deal with this @gatesyp? is it something we should add to the copy of the register node page?

**Comment by jacktrusler** [comment]
Closing this in favor of the design work that @WillDosSantos is doing. This should fix the problems we're having with confusion surrounding node creation.
