### ISSUE TITLE
Countdown timer on special URL for Steve

### ISSUE THREAD

**Issue by 0xJohnnyGault** [multisig-labs/app.gogopool.com#372]
# add countdown timer on dashboard (or website) of the eligibility cutoff date , and when rewards happen 

and showing the min and max rewards people have earned

(and can link it out to calculator)

## Description

- 

- duplicate the Welcome page redesign on its own endpoint:
    - app.gogopool.com/learn-about-minipools
    - add a countdown timer to it @WillDosSantos

**Comment by will** [comment]
ok, but what should it count down to?

**Comment by jacktrusler** [comment]
Closed with PR #379
