### ISSUE TITLE
Dashboard Redesign - My Rewards

### ISSUE THREAD

**Issue by WillDosSantos** [multisig-labs/app.gogopool.com#392]
**Problem**
My rewards, and rewards in general are super unclear through the UI right now. What am I getting rewarded? When is this happening? Why don't I see anything? How are rewards determined? There is just not enough information and right now the process feels very un-rewarding and un-motivating.

**Solution**
My Rewards card will have a new design that answers how the rewards are calculated, when you receive them and how much to expect. There will be multiple states for this card depending on what stage of the process the customer is at.

[Blank State Comp](https://www.figma.com/file/UMPEc0eW9iZyx5UlBXpCdi/Product-Design---GoGoPool?type=design&node-id=4560%3A11499&mode=design&t=y2lLh7GqhvHOAPWh-1)
[My Rewards - MP Prelaunch](https://www.figma.com/file/UMPEc0eW9iZyx5UlBXpCdi/Product-Design---GoGoPool?type=design&node-id=4460%3A26521&mode=design&t=y2lLh7GqhvHOAPWh-1)
[My Rewards - MP Validating](https://www.figma.com/file/UMPEc0eW9iZyx5UlBXpCdi/Product-Design---GoGoPool?type=design&node-id=4887%3A33265&mode=design&t=y2lLh7GqhvHOAPWh-1)
[My Rewards - MP Complete w/ Tooltips](https://www.figma.com/file/UMPEc0eW9iZyx5UlBXpCdi/Product-Design---GoGoPool?type=design&node-id=4230%3A8269&mode=design&t=y2lLh7GqhvHOAPWh-1)

**Comment by jacktrusler** [comment]
related to #421

**Comment by WillDosSantos** [comment]
@jacktrusler I updated the rewards card states here:
https://www.figma.com/file/UMPEc0eW9iZyx5UlBXpCdi/Product-Design---GoGoPool?type=design&node-id=5086%3A17761&mode=design&t=uGf2yUiNQ3Acr7FL-1

**Comment by WillDosSantos** [comment]
- [ ] Once you create your Minipool, if you are first in the queue the phrasing of the title is `Your validator is 0th in the queue.` Should probably read "You're first in queue!"

@jacktrusler

**Comment by jacktrusler** [comment]
Fixed the code, it will say `Your validator is 1st in the queue!` similarly to the rest.
