### ISSUE TITLE
EPIC: Create Minipool Redesign

### ISSUE THREAD

**Issue by WillDosSantos** [multisig-labs/app.gogopool.com#445]
## Making a minipool is too confusing! 

we’ve gotten feedback from users that there is too much friction in launching a minipool. (and generally, we should be identifying and knocking down any barriers we learn of for people to sign up with a minipool)

previously, it seemed like the biggest friction point was knowledge/onboarding - so we shipped the Welcome Page Redesign. that seemed to do the trick, especially for our target market at the time (which were Avalanche maxis/enthusiasts). 

now, we want to broaden our target market a bit to the general AVAX validator population (still mainly the non-whales / retail market). 

the main friction for them is that currently, that are clicking through 3 different platforms and signing a ton of txs (on gogopool: approve, stake, create; tj: find the ggp<>avax pool, swap the correct amount of avax; first choose hw provider, on allnodes/oonodz; swipe CC, create node, find and grab nodeid).

## lets make it one click easy
we want to give them a one click way to launch a minipool, giving them an “express installation” feel where they just pay 1 AVAX tx upfront and the minipool is created correctly. 

for advanced users, we give them “advanced options” to use their own NodeID and stake ggp tokens.

at a super high level, here are the components: 

![Image](https://github.com/multisig-labs/app.gogopool.com/assets/13278417/cbe2f8bb-2935-4844-96ba-8abcbf2eb0a9)
The create screen lets a user input AVAX and create a minipool directly. We assume they need to generate a NodeID. No need to stake GGP tokens separately. 

They still choose their own validation period, and cycling still happens normally. 

The main points on this screen are: 
1/ input how much AVAX you want to use to bootsrap the minipool
2/ view the "confirmation" details in real time to understand what kind of minipool is getting created, and what the expected rewards will be (bonus points for showing off the ROI vs running solo)

![Image](https://github.com/multisig-labs/app.gogopool.com/assets/13278417/21da7442-c8a4-4023-bb79-32f5fa78c652)
If the user has their own hardware, they can click "advanced options" to paste in their own NodeID. They can also stake more GGP tokens here. 

![Image](https://github.com/multisig-labs/app.gogopool.com/assets/13278417/fcfc9ac0-986e-4ed6-9c4d-fffea6e10f14)
After they click create, we want to reward them! 
1/ show them confetti! (or some similar visual cue)
2/ give some sort of mission-oriented copy
3/ have a "share on Twitter" cta

in the design, please keep in mind that we will want to add in surveys/CTAs to the end of this flow (eg an NPS survey, or "meet the founder" offer, or "stake more ggp to earn more rewards". they survey content is arbitrary -- the point here is that we need a composable element). 

### Implementing the "one click" experience?
A while ago, @0xju1ie and @0xJohnnyGault made the spike for BopIt: 
https://github.com/multisig-labs/gogopool-private/pull/10

This has the basic code for creating a minipool on behalf of a user. 
We can pair this with a Multicall contract: 
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Multicall.sol

So the multicall contract would handle the "stakeGGPOnBehalfOf", "createMinipoolOnBehalfOf", and "create nodeid through oonodz" calls. 

That would theoretically allow us to create a minipool using only one transaction. 

### They pay in AVAX, but GGP needs to be staked to create a minipool... how's that work?
Yes!
Note: @WillDosSantos the design probably needs to account for this, and somehow convey to the user that they are staking 1100 AVAX ... but 100 of that avax will turn into ggp tokens, staked on their behalf, and now they earn rewards in GGP tokens too. 

How it can work (example): 
1/ the user stakes 1100 avax
2/ the multicall swaps 100 avax for ggp tokens from the TraderJoe pool

I asked the TJ team for some sample solidity code, his response: 
```
We have some here:
- direct swap with the pair (less safe): https://github.com/traderjoe-xyz/joe-v2/blob/main/test/LBPairSwap.t.sol
- using the router (has safeguards etc): https://github.com/traderjoe-xyz/joe-v2/blob/main/test/LBRouter.Swap.t.sol

We can also generate something additional if there is a specific need you can elaborate on
```

So it sounds like they can help create the template code whenever we need. @0xju1ie i added you to the group chat with them, titled `GoGoPool x Joe`. 

### Generating a NodeID for the user
This might be a bit tricky to implement. When you are ready to start work on this, please **message Steven to introduce you to the Oonodz guys** -- we will use them as the default hardware provider. 

We don't have a technical spike on how the generation of NodeIDs on behalf of a user would work, so this would require some **fresh scoping** (and possibly has some rabbit holes). In future ShapeUps, John/Steven should probably spike it out. But because the Oonodz guys are so willing to work with us and help get GGP integrated, I think its still doable to both 1/ do the discovery work and 2/ implement it within this cycle. I recommend leaning on the Oonodz group as much as possible for this (they are very willing to build stuff for us). 

Probably start with spiking out and discovering this component! It seems the most technically risky, as we havent explored this. 

### How should they pay for the hardware?
There are a few approaches we considered for this. First, I thought "just have them pay in USDC on this page". But that seems like it increases the potential complexity for the user (now i need usdc in my wallet too? this was supposed to be easy! ), so I added an assumption that "users already have AVAX and want to pay in AVAX". 

Then, John had an idea of a "start now, pay later" scheme where users sign up for 1100 AVAX and pay for the hardware costs out of their AVAX or GGP rewards. This would make the upfront cost a bit lower, and logic a bit simpler (only need to modify rialto to withhold some rewards for people). Ultimately, I decided against this because: 
1/ who pays the hardware provider upfront? it would have to be us
2/ what if the user doesnt make enough rewards, or gets rewards slashed? we'd be stuck with the cost
3/ how would this be reflected in the UI? (I guess Will could do some magic, but we still need to make it clear that the hardware costs are being paid out of the rewards)

Overall, it seems to me like we can implement a "start now, pay later" scheme in coordination with something like a **Pandasia Phase2** (ie. Pandasia, but now its deployed cross chain). I think for the cross chain audience (who arent AVAX bulls) would like some sort of 'start now, pay later' method because they dont really care about AVAX in the first place. 

So, I've settled on a "pay upfront in AVAX" method. 

How it would work: 
1/ User comes to the page, sees that 1100 AVAX is pre-filled in the "stake" input box, and that NO validation period has been selected
2/ they select a validation period of say 30 days, and see that the AVAX price goes from 1100 to 1104 (assuming avax is at 10 dollars, and one month of Oonodz service is 40 USD)
3/ this increase in price is reflected in the receipt at the same time, making it clear to the user that the price increase is to pay for the hardware

This math should happen dynamically. 
EG the user selects 15 days, AVAX price in USD is 20 dollars, oonodz price is 40/mo -- the "stake" input box goes from "1100" to "1101"

Watch out for some edge cases here. EG. if a month is 28 days long, we need to double check if Oonodz charges for 28 days or 30 days. 

### Should we let the user make larger minipools through this? 
For now, we are still sticking to 2k minipools. 
BUT -- the technical design should 100% account for "turning on" the feature which allows people to make any sized minipools (eg. 5k on one side, get matched with 5k). 

Expect that we will want to turn that feature on in the next cycle. 

### How does cycling work with this?
Cycling works like normal, we aren't giving the users any options to mess with it. 

### The user already has GGP tokens in their wallet, what do? 
Under "Advanced Options", the user can stake all their GGP tokens. Lets say they have 50 AVAX worth of GGP tokens. If they decide to stake that, then the new minimum in the AVAX staking input box can become 1050. 

### The user wants to stake more GGP tokens than the minimum. How can we help them do so?
This is an awesome idea, and the design should account for this. What I'm imagining is: the user inputs 1100 AVAX in the staking box, and we show them a CTA saying "stake more AVAX to earn more rewards! <show excerpt of ggp token calculator>". 

In my opinion, we should definitely do this - but if we are running up against our timeline, this is the first feature to get cut. Its more of a "nice to have" versus "must have" at this point. If we cut it, we can run a small batch project (1-5 days) to implement a "GGP upsell during minipool creation". 

## Good ideas we arent focusing on right now (aka "stretch goals")
- "start now, pay later" schemes
- when user posts to twitter about their new minipool, automation to cross post the tweet to discord (and encourage everyone to "love bomb" it by rting and liking)

We can approach both of these as "small batch" work during next cycle, if we can't hit it on this cycle. 

## Intended supported usecases -- how do we know this is done? 
- Make creating a minipool a one click experience
- generate the NodeID for them
- show them a visual confirmation of success, make them feel like a winner

## KPIs influenced
- https://github.com/multisig-labs/pm/issues/46
- https://github.com/multisig-labs/pm/issues/44

**Comment by gatesyp** [comment]
Some notes from our call: 

## supported usecases
Make creating a minipool a one click experience
generate a NodeID button
experiment with buying GGP from our treasury in-app (instead of sending ppl to TJ)
### principles:
good innovative UX trumps conventional wisdom
lottery ticket feeling to launching a minipool, share that on twitter, auto post to discord, and like-bomb their tweet
yoinking design principles/ideas from gogopass

## KPIs

**Comment by gatesyp** [comment]
@WillDosSantos there are no figma designs for this yet right?

**Comment by WillDosSantos** [comment]
@gatesyp There are [designs here](https://www.figma.com/file/UMPEc0eW9iZyx5UlBXpCdi/Product-Design---GoGoPool?type=design&node-id=4722%3A12310&mode=design&t=S3RRFr9rDHll0pXK-1) for a redesign from what is currently on production - but the "one click" experience has not been addressed.

**Comment by 0xju1ie** [comment]
@gatesyp

1. Is this going to be the default design for all users? They come with AVAX only
2. In this design, do the users still get GGP Rewards? and upon validation completion can withdraw the 100 avax worth of GGP that we bought and staked for them?

**Comment by 0xju1ie** [comment]
we will need multisend, multicall is only for read txs. https://github.com/safe-global/safe-contracts/blob/main/contracts/libraries/MultiSend.sol

**Comment by 0xju1ie** [comment]
Im not sure if we will even need the multisend....

here is what I am thinking so far (for backend at least)

1. User stakes 1100+ avax into NewContract
2. 100 of that avax is sent to TJ pool and exchanged for GGP, and transferred back to this NewContract. This is the function I think we can use: https://github.com/traderjoe-xyz/joe-v2/blob/main/src/LBRouter.sol#L443
3. An [AuthorizedStaker](https://github.com/multisig-labs/gogopool-private/blob/447fbc6acdcc56332b6a03ad91d6b2335e25e3c0/contracts/contract/Staking.sol#L65) (can we add NewContract to this?) calls [stakeGGPOnBehalfOf()](https://github.com/multisig-labs/gogopool-private/blob/447fbc6acdcc56332b6a03ad91d6b2335e25e3c0/contracts/contract/Staking.sol#L353)
4. get NodeID from Oonodz somehow, either from the stake from the user or from their contracts directly. How do we pay them?
5. NewContract calls [createMinipoolOnBehalfOf()](https://github.com/multisig-labs/gogopool-private/pull/10/files#diff-22b5739fe1a2c482705a2c64836e0d0e734b2ad1353075b733569c7abd1ae916R216) with 1000 avax and NodeID

**Comment by 0xju1ie** [comment]
@gatesyp Will Oonodz accept AVAX from the user as payment for their services, or only USD?

Also, I think we should have them collateralized more than 10%, probably 15% to safeguard them from being kicked out of cycling

**Comment by gatesyp** [comment]
Only usdc / usdt

**Comment by gatesyp** [comment]
> Also, I think we should have them collateralized more than 10%, probably 15% to safeguard them from being kicked out of cycling

Why? Has it been a problem (or r u expecting it to be a problem)

**Comment by 0xju1ie** [comment]
> Why? Has it been a problem (or r u expecting it to be a problem)

since they are not buying GGP in the first place, they are likely going to set it and forget it - and when the time comes that they are under collat ratio they wont have the previous experience of buying GGP and staking it to work off of. Just seems like a higher probability for friction in their experience

**Comment by 0xju1ie** [comment]
> Only usdc / usdt

Will they budge from this?

**Comment by 0xju1ie** [comment]
After some further research, I dont think Multisend will ever work for our use case in the front end. Our goal was to have one approval click in meta mask for multiple transactions - such as staking avax, approving ggp, and staking ggp. As far as I can tell, this is something that meta mask determines - making the user approve each individual transaction. MetaMask seems like they do not have any plan to change that behavior: https://github.com/MetaMask/Design/issues/110

However, I _think_ Multisend would have a place in Rewards distribution and Pandatia - since its primary use case is airdropping tokens to multiple different addresses

**Comment by 0xJohnnyGault** [comment]
An approach for Oonodz integration, is to have them make a web2 API:

Our front end will first call:

`GET /getNextNodeID` 

`{nodeID: "NodeID-123"}` or `{error: "No nodes available, check back later!"}`

If we get a nodeID, then we call `/reserveNodeID` to mark that nodeID as reserved. Then we do all our web3 stuff, call the new contract with the nodeID, and on success, call 

`POST /claimNodeID   {nodeID: "NodeID-123", userAddr:"0x789", TxID: "0x456"}` and POST the txid and userAddr for their records.

On their side, they can time out if they see a `/reserveNodeID` not followed by a `/claimNodeID` in the following 10 min or something. So if the user starts the process and doesnt finish for whatever reason, they can release the node.

**Comment by 0xju1ie** [comment]
Wouldn't be easier for them to just make another contract function that streamlines all the calls they usually make?
https://docs.oonodz.network/VaaS-Avalanche/smart-contracts/smart-contract-overview/
looks like the typical flow is:
1. user registers
2. if they have a node id they call this one contract, if they don't they call another
3. user approves money transfer
4. user transfers money by starting a new subscription

What I want from oonodz is another function like newMinipool() that takes in a validation period and then registers the new user, takes the money, and returns a nodeID for us to use.

**Comment by WillDosSantos** [comment]
Completed
