### ISSUE TITLE
Gogopass 

### ISSUE THREAD

**Issue by jacktrusler** [multisig-labs/app.gogopool.com#481]
Related to Epic #445. Gogopass tab to be the place for a One-Click-Minipool flow. Most of the related info is in the Epic. 

Here is the related figma: https://www.figma.com/file/UMPEc0eW9iZyx5UlBXpCdi/Product-Design---GoGoPool?type=design&node-id=5692-14300&mode=design&t=YuWK1J6bZC6D669q-0

**Comment by WillDosSantos** [comment]
@jacktrusler We can close this and create a new issue if GoGoPass becomes a another feature but the functionality here has been accomplished with MPs 2.0
