### ISSUE TITLE
Create a tutorial on how to register a node

### ISSUE THREAD

**Issue by chand1012** [multisig-labs/app.gogopool.com#79]
![Image](https://user-images.githubusercontent.com/3521582/182422839-b807ebd2-3bda-4ce4-97de-369d8f84dbc3.png)

Currently this button does nothing. We should make a tutorial on how to register your node so you can earn on GoGoPool and link it with this button.

**Comment by 0xju1ie** [comment]
This button no longer exists, and the marketing/growth team is responsible for this
